"""make esp mac address unique

Revision ID: 08765ba00cf3
Revises: fd48417b67c0
Create Date: 2025-11-10 19:43:23.727411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08765ba00cf3'
down_revision: Union[str, Sequence[str], None] = 'fd48417b67c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esps_esp_mac_address'), table_name='esps')
    op.create_index(op.f('ix_esps_esp_mac_address'), 'esps', ['esp_mac_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esps_esp_mac_address'), table_name='esps')
    op.create_index(op.f('ix_esps_esp_mac_address'), 'esps', ['esp_mac_address'], unique=False)
    # ### end Alembic commands ###
