"""Update untuk menggunakan timezone Asia/Makassar

Revision ID: 20eb62ab4b14
Revises: 07bc2ce028d0
Create Date: 2025-12-05 13:42:07.363281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20eb62ab4b14'
down_revision: Union[str, Sequence[str], None] = '07bc2ce028d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
