"""feat: move start_time and end_time to base on FabricBoilingModel

Revision ID: 2666d8f8b58c
Revises: d2b6750ea2c9
Create Date: 2025-10-31 12:54:38.680611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2666d8f8b58c'
down_revision: Union[str, Sequence[str], None] = 'd2b6750ea2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
