"""Update boiling session and Sensor Data

Revision ID: 56ba15fcb597
Revises: 9b7646f9990c
Create Date: 2025-11-22 19:28:50.836860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56ba15fcb597'
down_revision: Union[str, Sequence[str], None] = '9b7646f9990c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_readings', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_sensor_readings_is_done'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_is_started'), table_name='sensor_readings')
    op.execute("ALTER TYPE status_enum ADD VALUE IF NOT EXISTS 'preparing'")
    op.execute("ALTER TYPE status_enum ADD VALUE IF NOT EXISTS 'canceled'")
    op.drop_column('sensor_readings', 'is_done')
    op.drop_column('sensor_readings', 'is_started')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('is_started', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_sensor_readings_is_started'), 'sensor_readings', ['is_started'], unique=False)
    op.create_index(op.f('ix_sensor_readings_is_done'), 'sensor_readings', ['is_done'], unique=False)
    op.alter_column('sensor_readings', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
