"""fix fabric_type model

Revision ID: 76930876ca47
Revises: 56ba15fcb597
Create Date: 2025-11-22 20:16:34.176725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '76930876ca47'
down_revision: Union[str, Sequence[str], None] = '56ba15fcb597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('fabric_types')]

    if 'boiling_temp' not in columns:
        op.add_column('fabric_types', sa.Column('boiling_temp', sa.Float(), nullable=False))
        op.drop_index(op.f('ix_fabric_types_temp'), table_name='fabric_types')
        op.create_index(op.f('ix_fabric_types_boiling_temp'), 'fabric_types', ['boiling_temp'], unique=False)
        op.drop_column('fabric_types', 'temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fabric_types', sa.Column('temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_fabric_types_boiling_temp'), table_name='fabric_types')
    op.create_index(op.f('ix_fabric_types_temp'), 'fabric_types', ['temp'], unique=False)
    op.drop_column('fabric_types', 'boiling_temp')
    # ### end Alembic commands ###
