"""initial clean schema

Revision ID: 92cfbc11e222
Revises: 
Create Date: 2025-10-30 18:47:20.738756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '92cfbc11e222'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabric_types',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('boiling_time', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabric_types_boiling_time'), 'fabric_types', ['boiling_time'], unique=False)
    op.create_index(op.f('ix_fabric_types_id'), 'fabric_types', ['id'], unique=False)
    op.create_index(op.f('ix_fabric_types_name'), 'fabric_types', ['name'], unique=False)
    op.create_index(op.f('ix_fabric_types_temp'), 'fabric_types', ['temp'], unique=False)
    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_password_hash'), 'users', ['password_hash'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('esps',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('esp_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esps_esp_uid'), 'esps', ['esp_uid'], unique=False)
    op.create_index(op.f('ix_esps_id'), 'esps', ['id'], unique=False)
    op.create_index(op.f('ix_esps_last_seen'), 'esps', ['last_seen'], unique=False)
    op.create_index(op.f('ix_esps_name'), 'esps', ['name'], unique=False)
    op.create_index(op.f('ix_esps_status'), 'esps', ['status'], unique=False)
    op.create_table('furnaces',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_furnaces_id'), 'furnaces', ['id'], unique=False)
    op.create_index(op.f('ix_furnaces_name'), 'furnaces', ['name'], unique=False)
    op.create_index(op.f('ix_furnaces_status'), 'furnaces', ['status'], unique=False)
    op.create_table('fabric_boiling_sessions',
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('esp_id', sa.Integer(), nullable=False),
    sa.Column('fabric_type_id', sa.Integer(), nullable=False),
    sa.Column('furnace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['esp_id'], ['esps.id'], ),
    sa.ForeignKeyConstraint(['fabric_type_id'], ['fabric_types.id'], ),
    sa.ForeignKeyConstraint(['furnace_id'], ['furnaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabric_boiling_sessions_id'), 'fabric_boiling_sessions', ['id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('water_temp', sa.Float(), nullable=False),
    sa.Column('air_temp', sa.Float(), nullable=False),
    sa.Column('is_started', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['fabric_boiling_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_air_temp'), 'sensor_readings', ['air_temp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_humidity'), 'sensor_readings', ['humidity'], unique=False)
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_is_done'), 'sensor_readings', ['is_done'], unique=False)
    op.create_index(op.f('ix_sensor_readings_is_started'), 'sensor_readings', ['is_started'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_water_temp'), 'sensor_readings', ['water_temp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_water_temp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_is_started'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_is_done'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_humidity'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_air_temp'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_fabric_boiling_sessions_id'), table_name='fabric_boiling_sessions')
    op.drop_table('fabric_boiling_sessions')
    op.drop_index(op.f('ix_furnaces_status'), table_name='furnaces')
    op.drop_index(op.f('ix_furnaces_name'), table_name='furnaces')
    op.drop_index(op.f('ix_furnaces_id'), table_name='furnaces')
    op.drop_table('furnaces')
    op.drop_index(op.f('ix_esps_status'), table_name='esps')
    op.drop_index(op.f('ix_esps_name'), table_name='esps')
    op.drop_index(op.f('ix_esps_last_seen'), table_name='esps')
    op.drop_index(op.f('ix_esps_id'), table_name='esps')
    op.drop_index(op.f('ix_esps_esp_uid'), table_name='esps')
    op.drop_table('esps')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password_hash'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fabric_types_temp'), table_name='fabric_types')
    op.drop_index(op.f('ix_fabric_types_name'), table_name='fabric_types')
    op.drop_index(op.f('ix_fabric_types_id'), table_name='fabric_types')
    op.drop_index(op.f('ix_fabric_types_boiling_time'), table_name='fabric_types')
    op.drop_table('fabric_types')
    # ### end Alembic commands ###
