"""add furnace endpoint and route

Revision ID: a19d4c8f8f86
Revises: 163742a322f9
Create Date: 2025-10-25 23:48:47.899634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a19d4c8f8f86'
down_revision: Union[str, Sequence[str], None] = '163742a322f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('furnaces',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_furnaces_id'), 'furnaces', ['id'], unique=False)
    op.create_index(op.f('ix_furnaces_name'), 'furnaces', ['name'], unique=False)
    op.create_index(op.f('ix_furnaces_status'), 'furnaces', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_furnaces_status'), table_name='furnaces')
    op.drop_index(op.f('ix_furnaces_name'), table_name='furnaces')
    op.drop_index(op.f('ix_furnaces_id'), table_name='furnaces')
    op.drop_table('furnaces')
    # ### end Alembic commands ###
