"""Update status ENUM

Revision ID: b59a72da1d43
Revises: 76930876ca47
Create Date: 2025-11-25 19:33:47.047214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59a72da1d43'
down_revision: Union[str, Sequence[str], None] = '76930876ca47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fabric_types_temp'), table_name='fabric_types')
    op.create_index(op.f('ix_fabric_types_boiling_temp'), 'fabric_types', ['boiling_temp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fabric_types_boiling_temp'), table_name='fabric_types')
    op.create_index(op.f('ix_fabric_types_temp'), 'fabric_types', ['boiling_temp'], unique=False)
    # ### end Alembic commands ###
