persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
# Optional: also show logs in docker
log_dest stdout
log_type all

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true
